Fix sql_test.yaml and migration 0000
Alexandra2706/Opening-db pull request #13
Opened 2024-04-02 16:00 UTC by Alexandra2706

2024-04-02 16:10 UTC, Artem3213212 commented on .github/workflows/sqls_test.yaml
> +  pull_request:
Наверное всетаки тоже добавим cюда:
```
    paths:
      - sqls/**
```

2024-04-02 16:12 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +CREATE TYPE kind AS ENUM ('tv', 'movie', 'ova');
`ona`, `other`

2024-04-02 16:12 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +CREATE TYPE kind_video AS ENUM ('pv', 'op', 'cm', 'ed');
`mv`

2024-04-02 16:12 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +CREATE TYPE status AS ENUM ('anons', 'ongoing', 'released');
Тут и далее IF NOT EXIST

2024-04-02 16:15 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +CREATE TABLE IF NOT EXISTS Images_table(
https://www.sqlshack.com/learn-sql-naming-conventions/ прочитай как в sql именуют таблицы и исправь

2024-04-02 16:16 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +CREATE TABLE emp (
Не понимаю что за таблица

2024-04-02 16:17 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +CREATE OR REPLACE FUNCTION check_values() RETURNS trigger AS $check_values$
название должно начинаться с имени таблицы иначае непонятно к чему отностится функция

2024-04-02 16:18 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +    --image integer REFERENCES Image (hash), --изображения на сайте shikimori
перенести из раздела шикимори и сделать обычный REFERENCES

2024-04-02 16:19 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +    anime_name varchar(255) UNIQUE NOT NULL, --название анимэ
переминуй в name

2024-04-02 16:20 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +    russian varchar(255), --название анимэ на русском
переминуй в name_russian  name_english .... name_synonyms

2024-04-02 16:21 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +    licensors jsonb, --лицензировано
licensors_ru

2024-04-02 16:23 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +    image_url varchar(255),  --ссылка на youtube картинка
пока закоментируй

2024-04-02 16:24 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +    hash varchar(64), --IPFS CID
`hash varchar(64) PRIMARY KEY,`  в остальных местах также

2024-04-02 16:25 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +    id uuid, --id студии
`id uuid PRIMARY KEY,`

2024-04-02 16:25 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +    image text --url логотипа студии
также как имадж у анимэ

2024-04-02 16:26 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +    filtered_name varchar(100), --надо?
пока закомменти

2024-04-02 16:26 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +        LOOP
давай LOOP писать на 1 строке с FOR

2024-04-02 16:27 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +     DECLARE
DECLARE на одном уровне с BEGIN лучше располагать

2024-04-02 16:28 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +    --Проверить что id_screenshot задан
--Проверить что id_screenshot задан верно (также и в других поправь)

2024-04-02 16:56 UTC, Artem3213212 requested changes

2024-04-02 16:56 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +    hosting varchar(100)
пока закоментируй

2024-04-02 16:56 UTC, Artem3213212 commented
1. Давай в мейк файле из `tests.postgres` вынесем `tests.postgres.migration` и `tests.postgres.test`
А потом напишем 2 подтеста: 1-ый как сечас, 2-й 2 раза вызываем `tests.postgres.migration` на пустом постгрессе (проверем что миграции сами себя не ломают)
2. Давай напишем тесты которые будут наполнять данными таблицы а потом читать из них.
3. Давай напишем цикл для поиска и запуска sql файлов миграций
4. Давай добавим индексы и напишем тесты с explain
5. Давай в отдельный файл `sqls/datagenerator.sql` напишем генерацию тестовых данных (может пригодится в других тетсах)

2024-04-02 18:57 UTC, Alexandra2706 commented on sqls/migrations/0000_init.sql
> +    anime_name varchar(255) UNIQUE NOT NULL, --название анимэ
name зарезервировано

2024-04-03 02:37 UTC, Artem3213212 requested changes

2024-04-03 02:39 UTC, Artem3213212 commented
!!Не забудь что надо написать все сущьности которые есть в прикрепленном тикете.

2024-04-05 23:01 UTC, Artem3213212 requested changes

2024-04-12 09:45 UTC, Artem3213212 requested changes

2024-04-12 09:45 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +        END IF;
отступы!

2024-04-16 18:40 UTC, Artem3213212 requested changes

2024-04-16 18:40 UTC, Artem3213212 commented on sqls/datagenerator/generator.sql
> +CREATE OR REPLACE FUNCTION stidio_generate() RETURNS VOID AS $stidio_generate$
опечатка в названии функции

2024-04-16 18:40 UTC, Artem3213212 commented on sqls/datagenerator/generator.sql
> +    row_number_genres integer := 0; --количество записей в таблице genres_table
row_number звучит плохо пройдись по всему файлу автозаменой и сделай total вместо row_number

2024-04-16 18:40 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +--CREATE TYPE IF NOT EXISTS status AS ENUM ('anons', 'ongoing', 'released');
или убери это или поставь каждый такой комментарий непосредственно перед строкой `DO $$ BEGIN ` которой он соответствует

2024-04-16 18:40 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +);
Неправильно.
Смотри как надо:
```
CREATE TABLE IF NOT EXISTS track_to_person(
    track_id uuid, --id трек-листа
    person_id boolean, --id человека
    role role,
    PRIMARY KEY (track_id, person_id),
);

CREATE INDEX track_to_person_reverse ON track_to_person USING B-Tree (person_id, track_id);
```

2024-04-16 18:40 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +CREATE TABLE IF NOT EXISTS track_list_to_person(
тоже самое что с track_to_person

2024-04-16 18:40 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +);
PS: тут еще надо refrences написать по идее.

2024-04-17 17:44 UTC, Artem3213212 approved these changes

2024-04-17 17:55 UTC, merged