add person
Alexandra2706/Opening-db pull request #27
Opened 2024-04-19 15:50 UTC by Alexandra2706

2024-05-03 17:00 UTC, Artem3213212 requested changes

2024-05-03 17:00 UTC, Artem3213212 commented on Makefile
> +	sleep 10
мы везде пишем `sleep 10` после `make local_run.start_postgres` мб его написать один раз в конец `local_run.start_postgres` ?

2024-05-03 17:00 UTC, Artem3213212 commented on jobs/shikimori-sync/main.go
> +	"strings"
Давай сразу правильно отсортируем импорты?

2024-05-03 17:00 UTC, Artem3213212 commented on jobs/shikimori-sync/main.go
> +	if err == nil {
обычно пишут наоборот
```
if err == nil {
   return ..., err
}
```

2024-05-03 17:00 UTC, Artem3213212 commented on jobs/shikimori-sync/main.go
> +	for _, i := range tempStr {
Используй встроенный replace! https://www.geeksforgeeks.org/strings-replace-function-in-golang-with-examples/

2024-05-03 17:00 UTC, Artem3213212 commented on jobs/shikimori-sync/main.go
> +	res, errCheck := CheckRowExists("genres_table", "id", stringId)
не надо выдумывать имена типо `errCheck` используй просто `err`

2024-05-03 17:00 UTC, Artem3213212 commented on jobs/shikimori-sync/main.go
> +	if res == false && errCheck == nil {
Не пиши `&& errCheck == nil`

Если возникла ошибка то сразу падай через
```
if err != nil {
    log.fatal(err)
}
```

2024-05-03 17:00 UTC, Artem3213212 commented on jobs/shikimori-sync/main.go
> +	res, errCheck := CheckRowExists("genres_table", "id", stringId)
Поиск надо делать по ключу `shikimori_id`. Тк теоритически англоязычное название могло поменяться. Сама функция проверки не удачная тк на выходе надо по мимо прочего понять какой id у записи(если не понимаешь по чему позвони мне я объясню).

2024-05-03 17:00 UTC, Artem3213212 commented on jobs/shikimori-sync/main.go
> +
Вобще надо еще случай когда genre_name или russian разошлись их обновлять.

2024-05-03 17:00 UTC, Artem3213212 commented on jobs/shikimori-sync/main.go
> +	res, errCheck := CheckRowExists("genres_table", "id", stringId)
Еще перед вызовом этой функции надо бы создать транзакцию.

2024-05-03 17:00 UTC, Artem3213212 commented on jobs/shikimori-sync/main.go
> +	query := fmt.Sprintf("SELECT %s FROM %s where %s = $1 limit 1", column, table, column)
SELECT ... FOR UPDATE (подробнее читай в кабане)

2024-05-03 17:00 UTC, Artem3213212 commented on jobs/shikimori-sync/main.go
> +	if err == sql.ErrNoRows {
https://github.com/jackc/pgx/wiki/Error-Handling

2024-05-03 17:00 UTC, Artem3213212 commented on jobs/shikimori-sync/shikimori-api/requests.go
> +		err := MakeRequest("animes/?limit=5&page="+strconv.Itoa(i)+"&order=id", animes)
это вероятно коммитить было ненадо

2024-05-03 17:00 UTC, Artem3213212 commented on sqls/migrations/0000_init.sql
> +    person_id uuid REFERENCES personCREATE INDEX IF NOT EXISTS track_to_person_reverse ON track_to_person USING BTREE (person_id, track_id);, --id человека
че это такое?

2024-05-20 10:20 UTC, Artem3213212 requested changes

2024-05-20 10:20 UTC, Artem3213212 commented on jobs/shikimori-sync/s3/s3.go
> +			return nil
эта строка не нужна тк ниж е все равно выходишь с nil

2024-05-20 10:20 UTC, Artem3213212 commented on jobs/shikimori-sync/s3/s3.go
> +	//	 - нет и поменялся mime type: загружаем новую картинку с новым именем, обновляем запись в БД, удаляем старую записьв БД
Этот коммент явно не там где код связанный с ним

2024-05-20 10:20 UTC, Artem3213212 commented on jobs/shikimori-sync/s3/s3.go
> +		log.Printf("Error in get hash object: %q", err.Error())
или отдавай ошибку или падай!

2024-05-20 10:20 UTC, Artem3213212 commented on jobs/shikimori-sync/s3/s3.go
> +		return err
Тут надо по пробовать удалить файл из S3

2024-05-20 10:20 UTC, Artem3213212 commented on jobs/shikimori-sync/s3/s3.go
> +		return err
у тебя даже в комменте об этом написано `// - при ошибке записи в таблицу, удалить файл из s3`

2024-05-20 10:20 UTC, Artem3213212 commented on jobs/shikimori-sync/s3/s3.go
> +package s3
Давай вынесем все функции с картинками в отдельный файл `s3/images.go`

2024-05-20 10:20 UTC, Artem3213212 commented on jobs/shikimori-sync/main.go
> +			err = s3.CreateOrUpdateImage(imageEndpoint + anime.Studios[i].Image)
Давай вынесем создание студии в отдельный новый модуль. Например `shikimori-sync/logic/studios.go`

2024-05-20 10:20 UTC, Artem3213212 commented on jobs/shikimori-sync/main.go
> +				log.Printf("Error in get image: %q", err.Error())
или отдавай ошибку или падай!

2024-05-20 10:20 UTC, Artem3213212 commented on jobs/shikimori-sync/main.go
> +		log.Printf("Error in list anime: %q", err.Error())
или отдавай ошибку или падай!

2024-06-10 21:56 UTC, Alexandra2706 commented
@Artem3213212 new commit

2024-06-11 16:28 UTC, Artem3213212 requested changes

2024-06-11 16:28 UTC, Artem3213212 commented on jobs/shikimori-sync/s3/image.go
> +		return err
Надо `DeleteFileFromS3(newPath)` перед этим ретурном, чтобы если CreateOrUpdateImage упал то мы файл почистили.

2024-06-11 16:28 UTC, Artem3213212 commented on jobs/shikimori-sync/s3/image.go
> +	dbImg := &postgres.Image{}
лишнее

2024-06-26 14:03 UTC, Artem3213212 requested changes

2024-07-02 11:32 UTC, Artem3213212 approved these changes

2024-07-02 11:32 UTC, merged