Init swagger
Alexandra2706/Opening-db pull request #29
Opened 2024-07-12 11:16 UTC by Alexandra2706

Add amine and person

2024-07-12 20:24 UTC, Artem3213212 requested changes

2024-07-12 20:24 UTC, Artem3213212 commented on api/Dockerfile
> +COPY routes ./
Тут не только routes надо добавить

2024-07-12 20:24 UTC, Artem3213212 commented on api/main.go
> +//func sayhello(w http.ResponseWriter, r *http.Request) {
это удалить пора

2024-07-12 20:24 UTC, Artem3213212 commented on api/main.go
> +	//mux.HandleFunc("/v1/anime", ListAnime)
это удалить пора

2024-07-12 20:24 UTC, Artem3213212 commented on api/postgres/anime.go
> +	//fmt.Println("ANIME LIST")
Подчисти пж

2024-07-12 20:24 UTC, Artem3213212 commented on api/postgres/person.go
> +		// ToDo: переделать внутри шикимори синк
Не забудь

2024-07-12 20:24 UTC, Artem3213212 commented on api/routes/anime.go
> +func SetLimitOffset(w http.ResponseWriter, r *http.Request) (*int, *int, error) {
Мб PrepareLimitOffset ?

2024-07-12 20:24 UTC, Artem3213212 commented on api/routes/anime.go
> +	jsonListPerson, err := json.MarshalIndent(&listPersonInfo, "", " ")
Просто Marshal

2024-07-12 20:24 UTC, Artem3213212 commented on api/routes/anime.go
> +	jsonListAnime, err := json.MarshalIndent(&listAnimeInfo, "", " ")
Просто Marshal

2024-07-12 20:24 UTC, Artem3213212 commented on api/routes/anime.go
> +	fmt.Printf("JSON string: %s\n", string(jsonListAnime))
Никаких fmt только log

2024-07-12 20:24 UTC, Artem3213212 commented on api/s3/s3.go
> +	"fmt"
никаких fmt

2024-07-12 20:24 UTC, Artem3213212 commented on api/s3/s3.go
> +	"fmt"
И проверь сразу что мы не оставили fmt в синке

2024-07-12 20:24 UTC, Artem3213212 commented on api/structures/kind.go
> +package structures
какой-то ненужный файл

2024-07-12 20:24 UTC, Artem3213212 commented on api/structures/status.go
> +//type JSONSet[T constraints.MyAnimeType] []T
Подчисти отсатки

2024-07-12 20:24 UTC, Artem3213212 commented on api/structures/status.go
> +	if v.Validate(enumValidator[reflect.TypeOf(s).Name()]) != nil {
Недоделано!

2024-07-12 20:24 UTC, Artem3213212 commented on api/structures/time.go
> +	//marshal_time := time.Now().UTC()
подчисти

2024-07-12 20:24 UTC, Artem3213212 commented on jobs/shikimori-sync/logic/person.go
> +	fmt.Println("TypeOf GrouppedRoles:", reflect.TypeOf(*person.GrouppedRoles))
Выглядит как лишнее

2024-08-02 11:41 UTC, Alexandra2706 commented on api/routes/anime.go
> +	jsonListPerson, err := json.MarshalIndent(&listPersonInfo, "", " ")
Он тогда все в одну строку выводит, очень неудобно проверять.

2024-08-19 19:33 UTC, Artem3213212 requested changes
Доделать

2024-08-23 21:41 UTC, Artem3213212 approved these changes

2024-08-23 21:41 UTC, merged